"""empty message

Revision ID: 5af2fe06e187
Revises: 3b0b9a1122eb
Create Date: 2018-11-21 11:00:51.684468

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5af2fe06e187'
down_revision = '3b0b9a1122eb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('temp_access_code', sa.String(length=200), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'temp_access_code')
    # ### end Alembic commands ###
